name: projeto_pac
description: A new Flutter project.

publish_to: 'none'


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^3.1.1
  provider: ^4.3.3

dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  http_interceptor:

flutter:
  uses-material-design: true
  assets:     
    - assets/burger-logo.png